# Page settings
baseurl = "antiodtes.app"
title = "Antidotes"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "info@antidotes.app"
  # Navigation
  [params.navigation]
    brand = "Antidotes"
    home = "Product"
    work = "Work"
    testimonials = "Testimonials"
    services = "Info"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Because you deserve quality, not a quick fix."
    subtitle = 'Access our Wellness <a href="https://www.cs4000.net/MyNutra/member/store/index.asp?pkg=1&sponsorid=717698&sponsorname=Caduceus%20Labs%20LLC" target="_blank" title="Antidotes Store">Store</a></a>'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Oil VS Paste"
    description = "100% of the industry is creating some form of an oil. Not only does this damage the healing attributes but it also greatly leaves an environmental footprint. Imagine all the machines and chemicals used to make CBD oil whereas Hemp Paste uses no chemicals or machines., Open the chart below for more details"
    url = "https://www.mynutra.com/wp-content/uploads/2018/08/Hemp-Paste_VS_CBD_OIL.png"
    button = "Chart"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Antidotes "
    description = "Antidotes is not only a company of herbal or hemp supplements, but of thinking and opportunity.  "
    url = ""
    button = "Coming Soon"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Guru System"
    description = "The guru system creates ownership that can be passed down and also does not require monthly upkeep alongside exposure to new perspective thinking, Receive your own buisness and product today. More options coming soon"
    url = "https://www.cs4000.net/MyNutra/enroll/signup_form.asp?pkg=1&sponsorid=717698"
    button = "Build a legacy"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=jhVjl5SdlTc"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Herbal Hemp supplements for the Endocannabinoid System and overall wellness. "

    [[params.testimonials.item]]
      quote = "&ldquo;The hemp paste helped my wife through speeding up the healing process of her foot.&rdquo;"
      person = 'Jeff" <span class="subtext">California</span>'

    [[params.testimonials.item]]
      quote = "&ldquo; I had Tonsillitis, was prescribed medication but still needed extra relief. The Hemp Paste worked wonders in fulfiling that duty &rdquo;"
      person = 'Clithy" <span class="subtext">California</span>'

    [[params.testimonials.item]]
      quote = "&ldquo;Not all the time I want to be high high, The paste gives me calmness without the need of feeling that way. &rdquo;"
      person = 'Happy" <span class="subtext">California</span>'




  # Services section
  [params.services]
    enable = true
    title = ""
    description = ' <br></a> <a href="https://www.projectcbd.org/science/endocannabinoid-system/endocannabinoid-system" target="_blank">Learn</a> about your Endocannabinoid System'

    [[params.services.item]]
      title = "Is the hemp used legal?"
      description = "Law stipulates that hemp must be less than .3% THC and Hemp Paste™ meets these guidelines. Hemp Paste™ is by legal terms “hemp”, but it is actually our proprietary strain of cannabis. This is a major breakthrough in our industry as most common hemp contains around .2% THC and, at best, 2 to 3% CBD. This means you need a lot of hemp to make a CBD product and most CBD products are heavily concentrated because of this. There are some complications in concentrating hemp and one of the complications is that the THC also gets concentrated during the process and then chemicals or strong solvents are added. This causes the natural structure to be altered. After over 4 years of crossbreeding and testing over 330 cannabis plants, our efforts delivered us a plant that tests at .24% THC and 19.37% CBD. The high strain of CBD means that we don’t have to use chemicals, butane, or CO2 to separate or concentrate our product. That alone sets Hemp Paste™ products apart from the rest of the industry."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "What is the guru system?"
      description = " Antidotes will scale through the addition of more products and education for the community to prosper or take part in disruptional projects. Initially the offer is to invest in your own buisness system that has no monthly fees and can be passed down or sold through MyNutras IBO system including the hemp paste, The only fee is 200$ which basically covers introductory tools and starting product."
      icon = "icon-layers2"
    
      [[params.services.item]]
      title = "U + 4"
      description = " Each team is divided by 5 and you can create as many teams as you want towards selling MyNutra product and spreading knowledge on the wonders of Hemp Paste."      
      icon = "icon-monitor"

  # Counters section
  [params.counters]
    enable = true
    title = "Happy Clients"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = ""
      icon = "icon-people"
      from = 0
      to = 47
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "If you have any questions in regards to the scope of Antidotes or in regards to any of the systems feel free to drop an email below"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-envelope", "info@antidotes.app"],
        ["icon-globe", '<a href="antidotes.app/" target="_blank">antidotes.app</a>']
      ]

    name = "Name"
    email = "Email"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; antidotes.app. All Rights Reserved'
    links = [
        ["icon-instagram", "#instagram"],
      ]
